### ISSUE TITLE
Error handling gifs with transparency 

### ISSUE THREAD

**Issue by SableWalnut** [torchbox/Willow#16]
I'm currently using wagtail (version 1.0rc2)  and as instructed per the documentation I had wand (version 0.4.0) installed and also have Willow installed from the latest git. I've tried processing a gif and expect that will work seamlessly however this is not the case. One of the images will simply not allow me to upload it (stacktrace below) the other continues to do as what was reported in wagtail issue #1084. 

Image 1
Stacktrace:
```
Internal Server Error: /admin/images/chooser/upload/
Traceback (most recent call last):
  File "/home/vagrant/bacontrols_venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/bacontrols_venv/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 43, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "/home/vagrant/bacontrols_venv/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/vagrant/bacontrols_venv/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/vagrant/bacontrols_venv/local/lib/python2.7/site-packages/wagtail/wagtailimages/views/chooser.py", line 140, in chooser_upload
    {'image_json': get_image_json(image)}
  File "/home/vagrant/bacontrols_venv/local/lib/python2.7/site-packages/wagtail/wagtailimages/views/chooser.py", line 22, in get_image_json
    preview_image = image.get_rendition('max-130x100')
  File "/home/vagrant/bacontrols_venv/local/lib/python2.7/site-packages/wagtail/wagtailimages/models.py", line 191, in get_rendition
    generated_image, output_format = filter.run(self, BytesIO())
  File "/home/vagrant/bacontrols_venv/local/lib/python2.7/site-packages/wagtail/wagtailimages/models.py", line 356, in run
    willow.save(willow.original_format, output)
  File "/home/vagrant/bacontrols_venv/local/lib/python2.7/site-packages/willow/image.py", line 67, in save
    return getattr(self, operation_name)(output)
  File "/home/vagrant/bacontrols_venv/local/lib/python2.7/site-packages/willow/image.py", line 28, in operation
    return func(self.backend, *args, **kwargs)
  File "/home/vagrant/bacontrols_venv/local/lib/python2.7/site-packages/willow/backends/pillow.py", line 81, in save_as_gif
    backend.image.save(f, 'GIF', transparency=backend.image.info['transparency'])
  File "/home/vagrant/bacontrols_venv/local/lib/python2.7/site-packages/PIL/Image.py", line 1703, in save
    save_handler(self, fp, filename)
  File "/home/vagrant/bacontrols_venv/local/lib/python2.7/site-packages/PIL/GifImagePlugin.py", line 376, in _save
    _get_local_header(fp, im, (0, 0), flags)
  File "/home/vagrant/bacontrols_venv/local/lib/python2.7/site-packages/PIL/GifImagePlugin.py", line 412, in _get_local_header
    transparency = int(transparency)
TypeError: int() argument must be a string or a number, not 'tuple'
```

I have attached below the images that I seem to be having issues with.

Image 1(Will not upload, stacktrace above)
![sedona-logo](https://cloud.githubusercontent.com/assets/10582038/8560179/c12c7df8-2558-11e5-8f3c-202efd364456.gif)
Image 2(Continues to fill transparent area with other colours as per wagtail issue torchbox/wagtail#1084, wand 0.4.0 is installed.)
![niagara-logo](https://cloud.githubusercontent.com/assets/10582038/8560180/c12fa85c-2558-11e5-8c65-cb7f7698c28c.gif)
Image 2 (Broken)
![niagara-logo focus-none original](https://cloud.githubusercontent.com/assets/10582038/8560293/ac5aec24-2559-11e5-8fa3-70e162bef1c0.gif)

**Comment by gsiegman** [comment]
I am running into this identical issue. I'm currently running Wagtail 1.0, Wand 0.4.0, Pillow 2.8.1, and Willow 0.2.1. Has there been a solution to fix this yet?

**Comment by ktosiek** [comment]
To everyone who'll stumble upon this issue - it's solved by https://github.com/sehmaschine/django-filebrowser/commit/b5923202758b69a9102b7453788d4362481faf40 which was apperently not released yet

**Comment by riceyrice** [comment]
I believe the stacktrace above on transparent GIFs was caused by a if/elif bug in wagtailimages/models.py causing a second attempt to save the same file. This got fixed some time ago.
