### ISSUE TITLE
IOError: cannot write mode P as JPEG

### ISSUE THREAD

**Issue by timheap** [torchbox/Willow#7]
When attempting to resize an image using the `{% image %}` template tag in Wagtail, I am getting the error: `IOError: cannot write mode P as JPEG`. According to a [question on StackOverflow](https://stackoverflow.com/questions/21669657/getting-cannot-write-mode-p-as-jpeg-while-operating-on-jpg-image), this is because JPEGs do not support P (palette?) mode images, and they must be converted to RGB mode before being saved:

```python
Image.open('old.jpeg').convert('RGB').save('new.jpeg')
```

Stack trace is below:

```
Internal Server Error: /admin/pages/174/edit/preview/
Traceback (most recent call last):
  File "/srv/acys-wagtail/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/acys-wagtail/venv/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 38, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "/srv/acys-wagtail/venv/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/srv/acys-wagtail/venv/src/wagtail/wagtail/wagtailadmin/views/pages.py", line 450, in preview_on_edit
    response = page.serve_preview(page.dummy_request(), preview_mode)
  File "/srv/acys-wagtail/venv/src/wagtail/wagtail/contrib/wagtailroutablepage/models.py", line 72, in serve_preview
    return view(request, *args, **kwargs)
  File "/srv/acys-wagtail/acys/utils/views.py", line 38, in proxy
    return self.view(request, page, *args, **kwargs)
  File "/srv/acys-wagtail/acys/yfx/views.py", line 57, in yfxedition_detail
    'prev_yfxedition': prev_yfxedition,
  File "/srv/acys-wagtail/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 50, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "/srv/acys-wagtail/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 178, in render_to_string
    return t.render(context_instance)
  File "/srv/acys-wagtail/venv/local/lib/python2.7/site-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/srv/acys-wagtail/venv/local/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/srv/acys-wagtail/venv/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/srv/acys-wagtail/venv/local/lib/python2.7/site-packages/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "/srv/acys-wagtail/venv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/srv/acys-wagtail/venv/local/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/srv/acys-wagtail/venv/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/srv/acys-wagtail/venv/local/lib/python2.7/site-packages/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "/srv/acys-wagtail/venv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/srv/acys-wagtail/venv/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/srv/acys-wagtail/venv/local/lib/python2.7/site-packages/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "/srv/acys-wagtail/venv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/srv/acys-wagtail/venv/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/srv/acys-wagtail/venv/local/lib/python2.7/site-packages/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "/srv/acys-wagtail/venv/src/wagtail/wagtail/wagtailimages/templatetags/wagtailimages_tags.py", line 55, in render
    rendition = image.get_rendition(self.filter)
  File "/srv/acys-wagtail/venv/src/wagtail/wagtail/wagtailimages/models.py", line 180, in get_rendition
    generated_image = filter.run(self, BytesIO())
  File "/srv/acys-wagtail/venv/src/wagtail/wagtail/wagtailimages/models.py", line 307, in run
    willow.save_as_jpeg(output)
  File "/srv/acys-wagtail/venv/local/lib/python2.7/site-packages/willow/image.py", line 29, in operation
    return func(self.backend, *args, **kwargs)
  File "/srv/acys-wagtail/venv/local/lib/python2.7/site-packages/willow/backends/pillow.py", line 65, in pillow_save_as_jpeg
    backend.image.save(f, 'JPEG', quality=quality)
  File "/srv/acys-wagtail/venv/local/lib/python2.7/site-packages/PIL/Image.py", line 1682, in save
    save_handler(self, fp, filename)
  File "/srv/acys-wagtail/venv/local/lib/python2.7/site-packages/PIL/JpegImagePlugin.py", line 571, in _save
    raise IOError("cannot write mode %s as JPEG" % im.mode)
IOError: cannot write mode P as JPEG
```

**Comment by timheap** [comment]
I will try to get the image in question and attach it so you can test it.

**Comment by timheap** [comment]
The images that are causing the issue are all PNG files in palette mode, not RGB mode. An example of this kind of image is: <http://takeflight.com.au/site-media/AWB_page_header.png>.

**Comment by timheap** [comment]
Bump

**Comment by kcidau** [comment]
I've \*ahem\* patched in a workaround, in the file `venv/local/lib/python2.7/site-packages/PIL/JpegImagePlugin.py` by changing this:

```python
def _save(im, fp, filename):

    try:
        rawmode = RAWMODE[im.mode]
    except KeyError:
        raise IOError("cannot write mode %s as JPEG" % im.mode)

    info = im.encoderinfo
```

to:

```python
def _save(im, fp, filename):

    try:
        if im.mode != "RGB":
            im = im.convert("RGB")
        rawmode = RAWMODE[im.mode]
    except KeyError:
        raise IOError("TRIGGER cannot write mode %s as JPEG" % im.mode)

    try:
        info = im.encoderinfo
    except AttributeError:
        info = im.info
```

**Comment by kaedroho** [comment]
This should be fixed in: https://github.com/torchbox/Willow/commit/0b31f85be514431c1ef4ff9c5b10b918b0de3669

This commit will be used by Wagtail when https://github.com/torchbox/wagtail/pull/1087 gets merged

**Comment by kaedroho** [comment]
This should be fixed in Wagtail now
